development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: virusdobem_development
  username: root
  password:
#  socket: /var/run/mysqld/mysqld.sock
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: virusdobem_production
  username: virusdobem
  password: ivb2015
