# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07df14155a507554c44dd71648de2b23a710ebca8f5382cd9c2c3060689a62f04b448266532d2fee385e851f501b09c7d88b599ba3c8fc74c063c2b719d03fe6

test:
  secret_key_base: 3702a26da1aa749c8e1190e400f34abc8e83c63a9a06fab6c184fba03c9f984256279a4ae90614ee69a8de2e3c3b9bd3f271d2bc9e24eb1f92f250fe7d99f7d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
